### ISSUE TITLE
ThiefCatcher crashes at startup

### ISSUE THREAD

**Issue by jonadem** [Ponup/thiefcatcher#6]
I got this crash when trying to run the game:

```
$ gdb ./Core/ThiefCatcher 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Core/ThiefCatcher...done.
(gdb) run
Starting program: /home/jona/dev/thiefcatcher/Core/ThiefCatcher 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2b06700 (LWP 7570)]
[Thread 0x7ffff2b06700 (LWP 7570) exited]
[New Thread 0x7ffff2b06700 (LWP 7571)]
[New Thread 0x7ffff089f700 (LWP 7572)]
[New Thread 0x7ffff085e700 (LWP 7573)]
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Thread 1 "ThiefCatcher" received signal SIGABRT, Aborted.
0x00007ffff775a7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff775a7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7745535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7b0d983 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7b138c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7b13901 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7b13b34 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b0f7d3 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555555f33e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=0x7fffffffdd90, __beg=0x0, 
    __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>)
    at /usr/include/c++/8/bits/basic_string.tcc:212
#8  0x00005555555adac4 in Properties::getProperty (this=0x7fffffffdcf0, propertyName=...)
    at /home/jona/dev/thiefcatcher/Kangaroo/src/Properties.cpp:77
#9  0x000055555558f0cb in Configurator::getLanguage[abi:cxx11]() const (this=0x7fffffffdcf0)
    at /home/jona/dev/thiefcatcher/Core/src/utilities/Configurator.cpp:25
#10 0x000055555555e042 in main (argc=1, argv=0x7fffffffdf08)
    at /home/jona/dev/thiefcatcher/Core/src/Main.cpp:64
```

What is wrong ?

**Comment by jonadem** [comment]
It works with this:

```
$ cd Core/
$ ./ThiefCatcher 
```
